services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pass123!"
    ports:
      - "1433:1433"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123!
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
